<font size = '4'><b> Flask Model Deployment </b></font>

<u>Dataset</u>: <i> Iris (scikit learn) </i>

<b> Import Libraries </b>

In [23]:
import numpy as np
import pandas as pd
import joblib
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
"""

We first import libraries that we need, such as numpy, pandas, and sklearn 
libraries used for machine learning. The toy dataset that is implemented 
in this example is the built-in scikit learn dataset "Iris".


After assigning the target to X and the variable to y, a train-test-split 
was performed to separate the training data from the test data, following 
up with standardizing our data with a StandardScaler.


The model implemented is Random Forest Classifier.


The file is then saved into a .pkl file to later be referenced in Flask.


>> The model has not been tuned as the sole purpose of this  <<
>> exercise is to have this model deployed on Flask Web App. <<


"""

<b>Load the Iris dataset from scikit learn</b>

In [15]:
# Loading the dataset (Iris) 
iris = datasets.load_iris()

# Features
X = iris.data

# Target variable (species)
y = iris.target

In [16]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [17]:
# Standardize feature scaling

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
# Create and train a Random Forest Classifier
clf = RandomForestClassifier(n_estimators=100, random_state=123)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=123)

In [19]:
# Make predictions on the test data
y_pred = clf.predict(X_test)

In [20]:
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

In [21]:
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(confusion)
print("Classification Report:")
print(classification_rep)

Accuracy: 0.93
Confusion Matrix:
[[13  0  0]
 [ 0  6  0]
 [ 0  2  9]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.75      1.00      0.86         6
           2       1.00      0.82      0.90        11

    accuracy                           0.93        30
   macro avg       0.92      0.94      0.92        30
weighted avg       0.95      0.93      0.93        30



In [24]:
# Save the model
joblib.dump(clf, 'model_iris.pkl')

['model_iris.pkl']